actiontech/dble-test-suite

behave_dble/features/func_test/cfg_test/schema_attribute.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case about issue:1177

behave_dble/compose/docker-build-behave/requirements.txt, drivers/Connector-J/pom.xml
=> improve security

drivers/c_mysql_api/src/ReadPrepareTest.cpp, drivers/c_mysql_api/src/WritePrepareTest.cpp, drivers/c_mysql_api/src/mysql_select_db.cpp, drivers/c_mysql_api/src/mysql_set_server_option.cpp
change variable declaration：from string-->char* to  const char*-->char*
=> change variable declaration

docs/使用文档/2. C-MySQL-API测试/2. C-MySQL-API测试.md, drivers/c_mysql_api/src/README.md
=> changes for running in Ubuntu

drivers/c_mysql_api/multi-queries/multiQuery.output
change the server ip in std file
=> change the server ip in std file

drivers/c_mysql_api/src/mysql_row_seek.cpp
=> fixed array overflow

drivers/c_mysql_api/src/c_mysql_api.cpp, drivers/c_mysql_api/src/c_mysql_api.output, drivers/c_mysql_api/src/c_mysql_api.sh, drivers/c_mysql_api/src/mysql_row_seek.cpp
skip “mysql_row_seek” for issue
=> skip “mysql_row_seek” for issue

drivers/c_mysql_api/src/c_mysql_api.output, drivers/c_mysql_api/src/mysql_real_query.cpp, drivers/c_mysql_api/src/null_in_sqlstr.cpp
=> fixed array overflows

drivers/c_mysql_api/src/ReadPrepareTest.cpp, drivers/c_mysql_api/src/WritePrepareTest.cpp
=> for prepare stmt

behave_dble/features/func_test/cfg_test/schema_attribute.feature, behave_dble/features/steps/restart.py
Reason:  
Type:  
Influences：  
   fix xx
=> add issue:1125 case

behave_dble/features/sql_cover/special/xa_transaction.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add issue:1116 case

behave_dble/features/func_test/safety/mysql_node_disconnected.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add issue:1144 case

drivers/c_mysql_api/src/ReadPrepareTest.cpp
resolved #1236 and marked the unsupportted part
=> resolved #1236 and marked the unsupportted part

behave_dble/sqls/sqls_mixed/bugs/bug.sql
=> for issue#1203

behave_dble/features/sql_cover/special/subquery_plan_optimize.feature, behave_dble/features/steps/resultset_compare.py, behave_dble/features/steps/step_reload.py
Reason:  
Type:  
Influences：  
   fix xx
=> add merge cases

behave_dble/dble_conf/sql_cover_sharding_bk/schema.xml, behave_dble/features/sql_cover/sql_sharding.feature, behave_dble/sqls/special_sharding/select/er_sharding.sql, behave_dble/std_sql_cover_sharding/special_sharding/select/er_sharding_pass.log
checking the RS from er table join
=> checking the RS from er table join

behave_dble/dble_conf/sql_cover_sharding_bk/schema.xml, behave_dble/features/sql_cover/special/hint.feature, behave_dble/features/sql_cover/sql_sharding.feature, behave_dble/sqls/special_sharding/select/er_sharding.sql, behave_dble/std_sql_cover_sharding/special_sharding/select/er_sharding_pass.log
er table join and multi-statement in ps
=> checking er table join and multi-statement in ps

behave_dble/features/sql_cover/special/hint.feature
checking the RS from multi-statement in pd
=> checking the RS from multi-statement in pd

drivers/java-interface/JDBCInterfaceTest/src/actiontech/dble/ConnectionTest.java
Reason:  
  Improve  
Type:  
  Improve  
Influences：  
  
=> print more info if itf_abort() failed

behave_dble/std_sql_cover_global/sqls_util/syntax/show_fail.log, behave_dble/std_sql_cover_global/sqls_util/syntax/show_pass.log, behave_dble/std_sql_cover_nosharding/sqls_util/syntax/show_fail.log, behave_dble/std_sql_cover_nosharding/sqls_util/syntax/show_pass.log, behave_dble/std_sql_cover_sharding/sqls_util/syntax/show_fail.log, behave_dble/std_sql_cover_sharding/sqls_util/syntax/show_pass.log
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
   fix xx
=> Req 21 for 2.19.07.0

behave_dble/features/sql_cover/special/subquery_plan_optimize.feature, behave_dble/sqls/sqls_util/dev_dealed/cross_db.sql, behave_dble/sqls/sqls_util/select/select.sql, behave_dble/std_sql_cover_global/sqls_util/select/select_fail.log, behave_dble/std_sql_cover_nosharding/sqls_util/select/select_fail.log, behave_dble/std_sql_cover_sharding/sqls_util/select/select_fail.log
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix #1251,1255,1256
=> for issue_1251_1255_1256

behave_dble/std_sql_cover_global/sqls_util/dev_dealed/cross_db_pass.log, behave_dble/std_sql_cover_nosharding/sqls_util/dev_dealed/cross_db_pass.log, behave_dble/std_sql_cover_sharding/sqls_util/dev_dealed/cross_db_pass.log
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix 1288
=> fixed issue 1288

behave_dble/features/func_test/cfg_test/charset.feature, behave_dble/features/func_test/cfg_test/server_system_value_valid.feature
Reason:  
   Improve #.  
Type:  
  Improve  
Influences：  
   fix xx
=> change the defalut charset from utf8 to utf8mb4

behave_dble/features/func_test/cfg_test/charset.feature
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
   fix xx
=> change default charset from utf8 to utf8mb4

behave_dble/features/cluster/xml_version_check.feature
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
   fix xx
=> skip the xml version check and add the new logic later

behave_dble/features/func_test/metalock/ddl_meta_lock.feature
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
   fix xx
=> skip metalock feature and add new logic later

behave_dble/features/func_test/managercmd/check_full_metadata.feature
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
   fix xx
=> align with the new logic of manage command

behave_dble/std_sql_cover_sharding/sqls_util/syntax/delete_fail.log, behave_dble/std_sql_cover_sharding/sqls_util/syntax/update_syntax_fail.log
Reason:  
  BUG .  
Type:  
  BUG  
Influences：  
   fix #751
=> fixed issssu 751

behave_dble/conf/logging.yaml, behave_dble/features/func_test/cfg_test/schema_stable.feature, behave_dble/features/steps/lib/XMLUtil.py
Reason:  
  BUG: fix string may be none, none has no lower()
=> Fix ci 1039 fail

behave_dble/features/cluster/xml_version_check.feature, behave_dble/features/steps/check_log.py, behave_dble/features/steps/resultset_compare.py
Reason:  
Type:  
Influences：  
   fix xx
=> add xml version case

behave_dble/README.md, behave_dble/behave.ini, behave_dble/compose/docker-build-general/Dockerfile, behave_dble/compose/start_dble_test.sh, behave_dble/features/environment.py, docs/QUICKSTART.md
Reason:  
Type:  
Influences：  
   fix xx
=> modify for install dble from local tar

behave_dble/compose/docker-build-behave/Dockerfile, behave_dble/compose/docker-build-behave/resetView.sh, behave_dble/compose/docker-build-general/Dockerfile, behave_dble/compose/start_dble_test.sh, behave_dble/conf/auto_test_dble_release.yaml, behave_dble/features/steps/lib/utils.py, behave_dble/features/steps/step_check_sql.py, behave_dble/features/steps/step_install.py
Reason:  
  BUG:   packet_name is not suite for install_from_local mode, fix: add new config for install_from_local and modify the packet_name usage
=> Install from local bug fix

behave_dble/features/func_test/managercmd/show_user.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix dble restart failed

behave_dble/features/sql_cover/sql_global.feature, behave_dble/features/sql_cover/sql_nosharding.feature, behave_dble/features/sql_cover/sql_sharding.feature, behave_dble/sqls/sqls_util/transaction/trx_savepoint.sql, behave_dble/std_sql_cover_global/sqls_util/transaction/trx_savepoint_pass.log, behave_dble/std_sql_cover_global/sqls_util/transaction/trx_savepoint_serious_warn.log, behave_dble/std_sql_cover_nosharding/sqls_util/transaction/trx_savepoint_pass.log, behave_dble/std_sql_cover_nosharding/sqls_util/transaction/trx_savepoint_serious_warn.log, behave_dble/std_sql_cover_sharding/sqls_util/transaction/trx_savepoint_pass.log, behave_dble/std_sql_cover_sharding/sqls_util/transaction/trx_savepoint_serious_warn.log
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
   fix xx
=> add savepoint into sql_cover

behave_dble/features/func_test/cfg_test/schema_attribute.feature, behave_dble/features/func_test/managercmd/show_user.feature
Reason:  
Type:  
Influences：  
   fix xx
=> for show @@user command

behave_dble/features/func_test/cfg_test/schema.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case about issue:1241

behave_dble/features/func_test/cfg_test/schema_attribute.feature, behave_dble/features/steps/restart.py
Reason:  
  change auto-test code try to excluding 1132 fail for mysql could not connect success
=> try to fix ci master 1132 fail

drivers/c_mysql_api/src/mysql_real_query.cpp
Reason:  
Type:  
Influences：  
   fix xx
=> for c api mysql_real_query()

behave_dble/features/func_test/cfg_test/server.feature, behave_dble/sqls/sqls_util/transaction/lock.sql, behave_dble/std_sql_cover_global/sqls_util/transaction/lock_pass.log, behave_dble/std_sql_cover_nosharding/sqls_util/transaction/lock_pass.log, behave_dble/std_sql_cover_sharding/sqls_util/transaction/lock_pass.log
Reason:  
  BUG  07_issue_1221_1374_1380
Type:  
  BUG
Influences：  
   fix xx
=> 07_issue_1221_1374_1380

drivers/c_mysql_api/src/c_mysql_api.cpp, drivers/c_mysql_api/src/mysql_change_user.cpp, drivers/c_mysql_api/src/mysql_reset_connection.cpp
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
   fix xx
=> COM_RESET_CONNECTION,COM_CHANGE_USER,COM_SET_OPTION

behave_dble/features/func_test/cfg_test/lower_case_table_names.feature, behave_dble/features/func_test/managercmd/check_column.feature, behave_dble/features/sql_cover/special/hint.feature, behave_dble/features/steps/step_function.py
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix #1229
=> about collation for issue #1229

drivers/Connector-.Net/netdriver/assets/sql/driver_test_manager.sql, drivers/Connector-J/assets/sql/driver_test_manager.sql, drivers/Connector-cpp/src/assets/sql/driver_test_manager.sql
Reason:  
Type:  
Influences：  
   fix xx
=> change for show @@directmemory

drivers/c_mysql_api/src/c_mysql_api.cpp, drivers/c_mysql_api/src/c_mysql_api.output
Reason:  
Type:  
Influences：  
   fix xx
=> replace standard output file

behave_dble/features/func_test/cfg_test/dataNode_caseSensitive.feature, behave_dble/features/func_test/cfg_test/lower_case_table_names.feature, behave_dble/features/sql_cover/special/subquery_plan_optimize.feature, behave_dble/features/steps/restart.py
Reason:  
  step desc is not clear 
Type:  
  Improve  
Influences：  
  
=> rename a step for restart mysql with options

behave_dble/features/cluster/check_full_meta_in_cluster.feature, behave_dble/features/cluster/ddl_in_cluster.feature, behave_dble/features/func_test/cfg_test/schema.feature, behave_dble/features/sql_cover/special/backquotes.feature, behave_dble/sqls/sqls_mixed/bugs/bug.sql, behave_dble/std_sql_cover_mixed/sqls_mixed/bugs/bug_pass.log
Reason:  
Type:  
Influences：  
   fix xx
=> 09issue_1323_1375_1386_1428 and testlink_7231

docs/测试点总结文档/TestPoints.md
Reason:  
  Improve #.  
Type:  
  Improve  
Influences：  
   fix xx
=> add testPoints document

behave_dble/features/cluster/zk_global_sequence.feature, behave_dble/features/func_test/sequence/ts_global_sequence.feature, behave_dble/features/steps/step_function.py, behave_dble/features/steps/step_reload.py
Reason:  
Type:  
Influences：  
   fix xx
=> dble-7238 format

behave_dble/conf/auto_test_dble_release.yaml, behave_dble/features/steps/step_install.py
Reason:  
Type:  
Influences：  
   fix xx
=> can install dble from Intranet or Extranet

behave_dble/features/sql_cover/special/sql_transformation.feature, behave_dble/features/steps/step_install.py, behave_dble/sqls/sqls_mixed/select/join_global_sharding.sql
Reason:  
Type:  
Influences：  
   fix xx
=> check the file after updated and add log if dble start failed

behave_dble/features/environment.py, behave_dble/features/func_test/managercmd/disable_enable_ha.feature, behave_dble/features/steps/step_check_sql.py, behave_dble/features/steps/step_configs.py
Reason:  
Type:  
Influences：  
   fix xx
=> try-to-fix: skip features still need file format check(maybe)

behave_dble/features/steps/lib/XMLUtil.py
Reason:  
Type:  
Influences：  
   fix xx
=> Add segment after node in xml util

behave_dble/conf/logging.yaml, behave_dble/features/steps/SqlUtil.py, behave_dble/features/steps/lib/XMLUtil.py
Reason:  
  BUG : refactor dataHost name made cfg_test/charset.feature failed fix
Type:  
Influences：  
   fix xx
=> fix_change_dataHost_name_fail

behave_dble/features/func_test/cfg_test/schema_attribute.feature
Reason:  
Type:  
Influences：  
   fix xx
=> heartbeat connection will create immediately after reload @@config_all

behave_dble/features/steps/step_reload.py, behave_dble/features/trace/trace_test.feature
=> turn on mysql trace and analyze sql with trace

behave_dble/features/func_test/sql_plan/cannot_route_single_node.feature, behave_dble/features/steps/step_reload.py
Reason:  
Type:  
Influences：  
   fix xx
=> some complex queries are not able to send one datanode

behave_dble/features/func_test/cfg_test/configuration_template_test.feature, behave_dble/features/steps/step_function.py, behave_dble/features/template_test/function_template.feature
Reason:  
Type:  
Influences：  
   fix xx
=> use template to generate configuration file, check function is normal

behave_dble/dble_conf/sql_cover_global_bk/server.xml, behave_dble/dble_conf/sql_cover_mixed_bk/server.xml, behave_dble/dble_conf/sql_cover_nosharding_bk/server.xml, behave_dble/dble_conf/sql_cover_sharding_bk/server.xml, behave_dble/dble_conf/template_bk/server.xml, behave_dble/features/func_test/managercmd/reload_config_recyclPool.feature, behave_dble/features/steps/restart.py, behave_dble/features/steps/resultset_compare.py
Reason:  
Type:  
Influences：  
   fix xx
=> reload @@config_all and recycl Pool

behave_dble/dble_conf/sql_cover_global_bk/server.xml, behave_dble/dble_conf/sql_cover_mixed_bk/server.xml, behave_dble/dble_conf/sql_cover_nosharding_bk/server.xml, behave_dble/dble_conf/sql_cover_sharding_bk/server.xml, behave_dble/dble_conf/template_bk/server.xml, behave_dble/features/func_test/managercmd/reload_config_all_fs.feature
Reason:  
Type:  
Influences：  
   fix xx
=> reload @@config_all -fs

behave_dble/dble_conf/sql_cover_global_bk/server.xml, behave_dble/dble_conf/sql_cover_mixed_bk/server.xml, behave_dble/dble_conf/sql_cover_nosharding_bk/server.xml, behave_dble/dble_conf/sql_cover_sharding_bk/server.xml, behave_dble/dble_conf/template_bk/server.xml, behave_dble/features/func_test/managercmd/reload_config_all_fr.feature, behave_dble/features/steps/restart.py
Reason:  
Type:  
Influences：  
   fix xx
=> reload @@config_all -fr

behave_dble/dble_conf/sql_cover_global_bk/server.xml, behave_dble/dble_conf/sql_cover_mixed_bk/server.xml, behave_dble/dble_conf/sql_cover_nosharding_bk/server.xml, behave_dble/dble_conf/sql_cover_sharding_bk/server.xml, behave_dble/dble_conf/template_bk/server.xml, behave_dble/features/func_test/managercmd/reload_config_all_sr.feature, behave_dble/features/steps/restart.py, behave_dble/features/steps/resultset_compare.py
Reason:  
Type:  
Influences：  
   fix xx
=> reload @@config_all -sr

behave_dble/dble_conf/sql_cover_global_bk/server.xml, behave_dble/dble_conf/sql_cover_mixed_bk/server.xml, behave_dble/dble_conf/sql_cover_nosharding_bk/server.xml, behave_dble/dble_conf/sql_cover_sharding_bk/server.xml, behave_dble/dble_conf/template_bk/server.xml, behave_dble/features/func_test/managercmd/reload_config_all_fsr.feature, behave_dble/features/steps/restart.py
Reason:  
Type:  
Influences：  
   fix xx
=> reload @@config_all -fsr

behave_dble/assets/BtraceClusterDelay.java, behave_dble/features/func_test/managercmd/reload_fault_tolerance.feature, behave_dble/features/steps/btrace_block.py
Reason:  
Type:  
Influences：  
   fix xx
=> execute manager cmd "reload @@config_all" and check fault tolerance

behave_dble/assets/BtraceDelayAfterDdl.java, behave_dble/features/cluster/show_ddl.feature, behave_dble/features/steps/btrace_block.py
Reason:  
Type:  
Influences：  
   fix xx
=> create feature "show_ddl.featrue"

behave_dble/features/func_test/cfg_test/metadata_fault_tolerance.feature, behave_dble/features/steps/btrace_block.py
Reason:  
Type:  
Influences：  
   fix xx
=> create file "metadata_fault_tolerance.feature"

behave_dble/features/func_test/cfg_test/mulitiple_reload.feature, behave_dble/features/steps/btrace_block.py, behave_dble/features/steps/step_reload.py
Reason:  
Type:  
Influences：  
   fix xx
=> create file "mulitiple_reload.feature"

behave_dble/features/func_test/sequence/ts_global_sequence.feature
Reason:  
Type:  
Influences：  
   fix xx
=> remove tag "@skip_restart"

behave_dble/features/cluster/kill_ddl_lock.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Keep kill ddl lock

behave_dble/features/environment.py, behave_dble/features/func_test/global_var_init/restore_global_var_when_reload.feature, behave_dble/features/steps/SqlUtil.py, behave_dble/features/steps/step_reload.py
Reason:  
Type:  
Influences：  
   fix python driver upgrade leads all 'error totally whack' related case fail
All testers please upgrade your own test env
=> modify code for upgrade python driver leads case fail

behave_dble/features/func_test/ddl/ddl_refactor.feature, behave_dble/features/steps/step_function.py
1.check log when ddl execute failed
2.check log when ddl execute successfully
3.check warning log when the time of hang>60s
Reason:  
Type:  
Influences：  
   fix xx
=> add 75% case ddl-refactor

behave_dble/dble_conf/template_bk/schema.xml, behave_dble/features/environment.py, behave_dble/features/func_test/cfg_test/schema_attribute.feature, behave_dble/features/func_test/cfg_test/schema_load_balance.feature, behave_dble/features/func_test/global_var_init/restore_global_var_when_reload.feature, behave_dble/features/func_test/global_var_init/start_fail_if_lettercase_different.feature, behave_dble/features/steps/MySQLObject.py, behave_dble/features/steps/RestoreEnvFactory.py, behave_dble/features/steps/SqlUtil.py, behave_dble/features/steps/lib/utils.py, behave_dble/features/steps/restart.py, behave_dble/features/steps/step_check_sql.py, behave_dble/features/steps/step_createConn.py, behave_dble/features/steps/step_function.py, behave_dble/features/steps/step_install.py, behave_dble/features/steps/step_reload.py
Reason:  
  append new cases for autocommit/isolation feature
Type:  
Influences：  
   fix xx
=> Autocommit func

behave_dble/features/steps/MySQLSteps.py
Reason:  
Type:  
Influences：  
   fix xx
=> fix bug for get node fail

behave_dble/features/func_test/cfg_test/schema_load_balance.feature, behave_dble/features/func_test/safety/safety.feature, behave_dble/features/sql_cover/special/hint.feature, behave_dble/features/steps/dble_steps.py, behave_dble/features/steps/lib/Flag.py, behave_dble/features/steps/lib/MySQLObject.py, behave_dble/features/steps/lib/ObjectFactory.py, behave_dble/features/steps/lib/PostQueryCheck.py, behave_dble/features/steps/mysql_steps.py
Reason:  
  select 10000 times in single thread mode spent too long, optimize it by using concurrent
Type:  
Influences：  
   fix xx
=> Optimize concurrnt select

behave_dble/assets/BtraceXaDelay_backgroundRetry.java, behave_dble/features/func_test/xa_transaction/bg_strategy_after_net_shock.feature, behave_dble/features/func_test/xa_transaction/bg_strategy_after_node_hangs.feature, behave_dble/features/func_test/xa_transaction/kill_node_before_commit.feature, behave_dble/features/func_test/xa_transaction/kill_node_before_rollback.feature, behave_dble/features/func_test/xa_transaction/single_node_connect_exception.feature, behave_dble/features/func_test/xa_transaction/xa_node_result_diff.feature, behave_dble/features/func_test/xa_transaction/xa_retry_count.feature, behave_dble/features/steps/dble_steps.py
Reason:  
Type:  
Influences：  
   fix xx
=> change for xa refactor

drivers/java/sh/jdbc-api-test-start.sh, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/StatementTest.java
Reason:  
  BUG 
Type:  
  BUG 
Influences：  
  fix: show warnings need make shardingnode
=> fix: show warnings need make shardingnode

drivers/java/sh/jdbc-api-test-start.sh
Reason:  
   Improve
Type:  
  Improve  
Influences：  
  update packaging script
=> fix: update packaging script

drivers/java/sh/jdbc-api-test-start.sh
Reason:  
  Improve
Type:  
  Improve  
Influences：  
  update filename
=> fix: update filename

drivers/java/sh/jdbc-api-test-start.sh, drivers/jdbc-api-test/pom.xml
Reason:  
  Improve
Type:  
  Improve  
Influences：  
  update sh
=> fix: update sh

drivers/jdbc-api-test/src/main/java/com/actiontech/dble/Main.java
Reason:  
   Improve 
Type:  
  Improve  
Influences：  
  fix: Set debug to false
=> fix: Set debug to false

behave_dble/features/sql_cover/special/dml_penetrate.feature, behave_dble/features/sql_cover/special/dml_penetrate_test.feature
=> add dml penetrate

behave_dble/features/func_test/cfg_test/dbInstance_load_balance.feature, behave_dble/features/func_test/cfg_test/db_stable.feature, behave_dble/features/func_test/global_var_init/restore_global_var_when_reload.feature, behave_dble/features/func_test/global_var_init/start_fail_if_lettercase_different.feature, behave_dble/features/func_test/managercmd/check_full_metadata.feature, behave_dble/features/func_test/managercmd/reload_config_all.feature, behave_dble/features/func_test/managercmd/show_dbinstance.feature, behave_dble/features/func_test/safety/mysql_node_disconnected.feature, behave_dble/features/func_test/xa_transaction/bg_strategy_after_node_hangs.feature, behave_dble/features/func_test/xa_transaction/kill_node_before_commit.feature, behave_dble/features/func_test/xa_transaction/kill_node_before_rollback.feature, behave_dble/features/func_test/xa_transaction/xa_retry_count.feature, behave_dble/features/steps/RestoreEnvObject.py, behave_dble/features/steps/lib/MySQLObject.py
Reason:  
Type:  
Influences：  
   fix xx
=> add restore mysql service after scenario

drivers/c_mysql_api/multi-queries/multiQuery.output, drivers/c_mysql_api/multi-queries/mysql_multi_queries.cpp
Reason:  
Type:  
Influences：  
   fix xx
=> add case for github issue 1806

behave_dble/features/cluster/ruleFile.feature, behave_dble/features/func_test/cfg_test/ruleFile.feature, behave_dble/features/steps/check_zk_meta.py, behave_dble/features/steps/step_reload.py
Reason:  
  http://10.186.18.11/jira/browse/DBLE0REQ-38
Type:  
  Improve  
Influences：  
  single node & ZK cluster
=> DBLE0REQ-38 ruleFile 

behave_dble/features/func_test/route_management/dble_db_group.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add the case of insert\update\delete about dble_information

behave_dble/assets/all_schemas_with_data.sql, behave_dble/assets/noschema_only_table_data.sql, behave_dble/assets/schema1_with_data.sql, behave_dble/assets/schema1_with_data_special.sql, behave_dble/assets/schema1_with_only_data.sql, behave_dble/features/func_test/managercmd/split.feature, behave_dble/features/steps/step_function.py
Reason:  
  DBLE0REQ-35, DBLE0REQ-94, DBLE0REQ-513
Type:  
Influences：  
   fix xx
=> add split cases

behave_dble/features/func_test/sql_plan/route_single_node_across_databases.feature
route_single_node_across_databases.feature
=> add case about route_single_node_across_databases.feature

behave_dble/features/func_test/cfg_test/view.feature
Reason:  
  autotest for dble request number 66 
Type:  
  Improve  
Influences：  
   fix xx
=> add vertical view case

behave_dble/features/func_test/managercmd/slow_query.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case about slowquery

behave_dble/std_sql_cover_global/sqls_util/transaction/trx_syntax_fail.log, behave_dble/std_sql_cover_global/sqls_util/transaction/trx_syntax_pass.log, behave_dble/std_sql_cover_nosharding/sqls_util/transaction/trx_syntax_fail.log, behave_dble/std_sql_cover_nosharding/sqls_util/transaction/trx_syntax_pass.log, behave_dble/std_sql_cover_sharding/sqls_util/transaction/trx_syntax_fail.log, behave_dble/std_sql_cover_sharding/sqls_util/transaction/trx_syntax_pass.log
http://10.186.18.11/jira/browse/DBLE0REQ-607
=> ci_fixed,support begin work syntax

drivers/Connector-J/conf/auto_dble_test.yaml, drivers/Connector-J/src/main/java/com/actiontech/Config.java, drivers/Connector-J/src/main/java/com/actiontech/testJDBC.java, drivers/Connector-J/src/main/java/com/actiontech/yamlParser.java
Reason:  
  BUG 
Type:  
  BUG  
Influences：  
  fix: connector-J modify the management side schema to dble_information
=> fix: connector-J modify the management side schema to dble_information

drivers/Connector-J/conf/auto_dble_test.yaml, drivers/Connector-J/src/main/java/com/actiontech/Config.java, drivers/Connector-J/src/main/java/com/actiontech/testJDBC.java, drivers/Connector-J/src/main/java/com/actiontech/yamlParser.java
Reason:
  BUG
Type:
  BUG
Influences：
  fix: connector-J modify the management side schema to dble_information
#210
=> fix: connector-J modify the management side schema to dble_information(cherry-pick from master #210)

behave_dble/features/func_test/heartbeat/reconnect_heartbeat_readonly_check.feature, behave_dble/features/func_test/reconnect_heartbeat_readonly_check.feature
Reason:  
  add new feature  http://10.186.18.11/jira/browse/DBLE0REQ-80
Type:  
Influences：  
   fix xx
=> keep_DBLE0REQ-80

behave_dble/assets/Btrace.md
Reason:  
  Improve inner-433
Type:  
  Improve  
Influences：  
   add btrace doc
=> add btrace doc

drivers/java/sh/jdbc-api-test-start.sh
Reason:  
Type:  
Influences：  
   fix xx
=> Fix ci driver fail

behave_dble/features/func_test/cfg_test/performance.feature
Reason:  
 http://10.186.18.11/jira/browse/DBLE0REQ-699  
Type:  
  Improve  
Influences：  
   fix xx
=> add turn on performanceMode test

behave_dble/features/func_test/cfg_test/sqlMaxLimit.feature
Reason:  
  http://10.186.18.11/jira/browse/DBLE0REQ-720
Type:  
Influences：  
   fix xx
=> add sqlMaxLimit cases

behave_dble/features/func_test/sql_plan/complexQuery_sendTo_oneNode.feature.feature, behave_dble/features/steps/resultset_compare.py
Reason:  
Type:  
Influences：  
   fix xx
=> Keep explain

behave_dble/features/func_test/managercmd/dryrun.feature
Reason:  
Type:  
Influences：  
   fix xx
=> change dryrun feature

drivers/c_mysql_api/multi-queries/multiQuery.sh
Reason:  
  http://10.186.18.11/jira/browse/DBLE0REQ-729 
Type:  
Influences：  
   fix xx
=> change to correct dir before executing make clean

behave_dble/features/func_test/managercmd/slow_query.feature
add slowlog case about what's NODE_QUERY  http://10.186.18.11/jira/browse/DBLE0REQ-503
=> slowlog_DBLE0REQ-503

behave_dble/features/func_test/global_var_init/restore_global_var_when_reload.feature, behave_dble/features/steps/lib/MySQLObject.py, behave_dble/features/steps/server_step.py
Reason:  
  fix function kill_all_conns
Type:  
  BUG 
Influences：  
   http://10.186.18.19:8153/go/pipelines/autotest-dble-master/1715/manager/1
features/func_test/global_var_init/restore_global_var_when_reload.feature:96  set global vars failed for user has no priviledges, then set session context if values are not same as config at conn used #4
=> Ci master 1715

behave_dble/features/cluster/zk_onlinekey_check.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add check online key about DBLE0REQ-32

behave_dble/features/func_test/managercmd/reload_config_all_f.feature, behave_dble/features/func_test/safety/set_sql_select_limit.feature, behave_dble/features/func_test/sql_plan/route_single_node_across_databases.feature, behave_dble/features/sql_cover/special/backquotes.feature, behave_dble/features/sql_cover/special/support_special_sql.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case about github issue

behave_dble/features/func_test/cfg_test/db_value_incorrect.feature, behave_dble/features/func_test/cfg_test/sharding_value_incorrect.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add xml check

behave_dble/compose/docker-build-behave/Dockerfile, behave_dble/compose/docker-build-general/Dockerfile
Reason:  
  DBLE0TASK-340 & DBLE0TASK-422
Type:  
  Improve  
Influences：  
   update images
=> Feature dble_task 340 422

behave_dble/compose/docker-build-driver/Dockerfile
Reason:  
  update Dockerfile for 'install mysql on docker image dble/dble_test_driver:latest '
Type:  
  Improve  
Influences：  
    fix   DBLE0REQ-752
=> fix  DBLE0REQ-752

.github/auto_assign.yml, .github/workflows/Auto_Review.yml
Reason:  
Type:  
Influences：  
   fix xx
=> add auto assign reviewer

behave_dble/assets/BtraceSessionStage.java, behave_dble/features/func_test/connection/kill_front_connection.feature, behave_dble/features/steps/step_parameter.py
Reason:  
Type:  
Influences：  
   fix xx
=> add about DBLE0REQ-726 and DBLE0REQ-12

behave_dble/features/steps/btrace_block.py
Reason:  
Type:  
Influences：  
   fix xx
=> update assert condition

behave_dble/assets/BtraceFreshConnLock.java, behave_dble/features/func_test/managercmd/freshConn.feature, behave_dble/features/func_test/managercmd/pause_resume.feature, behave_dble/features/steps/dble_steps.py
Reason:  
  from http://10.186.18.11/jira/browse/DBLE0REQ-351
Type:  
Influences：  
   fix xx
=> add more fresh connection cases

behave_dble/compose/docker-build-behave/ChangeMaster.sh, behave_dble/features/cluster/cluster_check_Ha.feature
Reason:  
Type:  
Influences：  
   fix xx
=> modify ChangeMaster

drivers/jdbc-api-test/src/main/java/com/actiontech/dble/CapClientFoundRowsTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/Config.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/Main.java
Reason:  
Type:  
Influences：  
   fix xx
=> add for DBLE0REQ-354

behave_dble/assets/BtraceClusterDelay.java, behave_dble/features/cluster/cluster_check_pause_resume.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Keep check pause

behave_dble/compose/docker-build-behave/Dockerfile
Reason:  
  change timezone to CST DBLE0REQ-784
Type:  
  Improve  http://10.186.18.11/jira/browse/DBLE0REQ-784
Influences：  
   timezone of image dble/dble_test_client
=> change timezone to CST DBLE0REQ-784

behave_dble/assets/Btrace.md, behave_dble/assets/BtraceClusterDelay.java, behave_dble/features/cluster/cluster_check_table_ddl.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Keep check table ddl

behave_dble/features/func_test/managercmd/freshConn.feature, behave_dble/features/steps/btrace_block.py
Reason:  
  remove skip tag for fresh conn and fix http://10.186.18.11/jira/browse/DBLE0REQ-808
Type:  
Influences：  
   fix xx
=> remove skip tag and fix stop btrace hang

behave_dble/features/cluster/cluster_check_xa.feature
Reason:  
Type:  
Influences：  
   fix xx
=> keep_check_zk_xa

behave_dble/features/cluster/cluster_check_Ha.feature, behave_dble/features/cluster/cluster_check_table_view.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Keep check table view

behave_dble/compose/docker-build-behave/init_test_env.sh, behave_dble/compose/docker-build-behave/resetReplication.sh, behave_dble/compose/docker-compose.yml, behave_dble/conf/auto_dble_test.yaml, behave_dble/conf/auto_test_dble_release.yaml, behave_dble/features/func_test/sql_plan/test_group_by.feature
Reason:  
  Improve：http://10.186.18.11/jira/browse/DBLE0REQ-165  
Type:  
Influences：  
   fix xx
=> add group by cases

behave_dble/compose/start_env.sh
Reason:  
  Improve from: http://10.186.18.11/jira/browse/DBLE0REQ-821 
Type:  
Influences：  
   fix xx
=> copy the new init_test_env file into behave container

behave_dble/compose/docker-build-driver/Dockerfile
Reason:  
  install iptables on image dble/dble_test_driver
Type:  
Influences：  
   fix http://10.186.18.11/jira/browse/DBLE0REQ-819
=> install iptables on image dble/dble_test_driver

behave_dble/assets/BtraceClusterDelay.java, behave_dble/features/cluster/cluster_check_xa.feature, behave_dble/features/cluster/cluster_check_zk_binlog.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Keep check mysql binlog

behave_dble/features/cluster/cluster_txIsolation.feature, behave_dble/features/func_test/cfg_test/txIsolation.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add for DBLE0REQ-177 about txIsolation supports tx_/transaction_

behave_dble/compose/docker-build-behave/init_test_env.sh, behave_dble/compose/docker-build-behave/resetReplication.sh, behave_dble/compose/start_env.sh
Reason:  
Type:  
Influences：  
   fix xx
=> fix_DBLE0REQ-823

behave_dble/README.md
Reason:  
  Improve : http://10.186.18.11/jira/browse/DBLE0REQ-813 
Type:  
Influences：  
   fix xx
=> add tags desc

behave_dble/features/func_test/cfg_test/user.feature
Reason:  
  Improve： http://10.186.18.11/jira/browse/DBLE0REQ-548，http://10.186.18.11/jira/browse/DBLE0REQ-566
Type:  
Influences：  
   fix xx
=> add rwSplitUsers cases

behave_dble/features/func_test/cfg_test/view.feature, behave_dble/features/func_test/managercmd/python_mysql_ha.feature, behave_dble/features/sql_cover/special/chinese_comment.feature, behave_dble/features/sql_cover/special/support_special_sql.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case about DBLE0REQ-311

behave_dble/features/func_test/cfg_test/fake_mysql_version.feature, behave_dble/features/func_test/connection/mysql8_authentication_plugin.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update fakeMysqlVersion case

behave_dble/features/sql_cover/special/chinese_comment.feature
Reason:  
Type:  
Influences：  
   fix xx
=> about "HEX" and "QUOTE"

behave_dble/features/func_test/connection/mysql8_authentication_plugin.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add restore_mysql_config for mysql8.0 case

behave_dble/assets/BtraceSessionStage.java, behave_dble/features/func_test/connection/kill_front_connection.feature, behave_dble/features/func_test/slow_log/slowquery_stage_queryplan.feature, behave_dble/features/steps/step_parameter.py
Reason:  
Type:  
Influences：  
   fix xx
=> add for DBLE0REQ-79

behave_dble/features/func_test/cfg_test/shardingNode_caseSensitive.feature, behave_dble/features/func_test/cfg_test/sharding_value_incorrect.feature, behave_dble/features/func_test/cfg_test/user_value_incorrect.feature
Reason:  
  fix ci fail: http://10.186.18.19:8153/go/tab/build/detail/autotest-dble-master-108/2/manager/1/func_test 
Type:  
Influences：  
   fix xx
=> restore lower_case_table_name

behave_dble/assets/Btrace.md, behave_dble/assets/BtraceFreshConnLock.java, behave_dble/features/func_test/cfg_test/db_stable.feature, behave_dble/features/func_test/dble_information/dble_entry_group.feature, behave_dble/features/func_test/dble_information/table_support_select.feature, behave_dble/features/func_test/managercmd/freshConn.feature
Reason:  
  http://10.186.18.19:8153/go/pipelines/autotest-dble-master-108/2/manager/1
Type:  
Influences：  
   fix xx
=> fix master-108 instance 2

behave_dble/features/cluster/cluster_check_zk_binlog.feature, behave_dble/features/steps/RestoreEnvObject.py
Reason:  
Type:  
Influences：  
   fix xx
=> restore mysql config about master1 binlog

behave_dble/compose/docker-build-general/Dockerfile
Reason:  
  DBLE0REQ-834 add python3 dependency for custom_mysql_ha
Type:  
Influences：  
   fix http://10.186.18.11/jira/browse/DBLE0REQ-834
=> DBLE0REQ-834 add python3 dependency for custom_mysql_ha

drivers/java/sh/jdbc-api-test-start.sh, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/CapClientFoundRowsTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/Config.java
Reason:  
Type:  
Influences：  
   fix xx
=> add for DBLE0REQ-814

drivers/jdbc-api-test/src/main/java/com/actiontech/dble/CapClientFoundRowsTest.java
Reason:  
Type:  
Influences：  
   fix xx
=> update reset capClientFoundRows

drivers/Connector-.Net/netdriver/assets/sql/driver_test_manager.sql, drivers/Connector-J/assets/sql/driver_test_manager.sql, drivers/Connector-cpp/src/assets/sql/driver_test_manager.sql, drivers/Connector-cpp/std_sql_logs/driver_test_client_fail.log
Reason:  
Type:  
Influences：  
   fix xx
=> Keep fix ci driver

behave_dble/features/cluster/cluster_check_reload.feature, behave_dble/features/func_test/cfg_test/Exception_sharding.feature, behave_dble/features/func_test/cfg_test/db_value_incorrect.feature, behave_dble/features/func_test/cfg_test/sharding_value_incorrect.feature, behave_dble/features/func_test/cfg_test/user.feature, behave_dble/features/func_test/cfg_test/user_value_incorrect.feature, behave_dble/features/func_test/cfg_test/user_whiteIPs.feature, behave_dble/features/func_test/dble_information/dble_entry_group.feature
Reason:  
  BUG 
Type:  
  BUG
Influences：  
   fix: errors caused by xsd
=> fix: errors caused by xsd

behave_dble/features/func_test/ddl/online_ddl.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Keep onlineddl

behave_dble/features/cluster/cluster_txIsolation.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Fix ci about isolation in cluster

behave_dble/features/steps/step_install.py
Reason:  
Type:  
Influences：  
   fix xx
=> update for run cluster

behave_dble/features/steps/lib/MySQLObject.py
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue

behave_dble/assets/BtraceAboutConnection.java, behave_dble/features/func_test/connection/connection_pool_basic_test.feature
Reason:  
  Improve from: http://10.186.18.11/jira/browse/DBLE0REQ-246
Type:  
Influences：  
   fix xx
=> add cases about connection pool

behave_dble/features/func_test/cfg_test/lower_case_table_names.feature, behave_dble/features/func_test/cfg_test/schema_attribute.feature, behave_dble/features/func_test/cfg_test/schema_load_balance.feature, behave_dble/features/func_test/cfg_test/server.feature, behave_dble/features/func_test/managercmd/check_full_metadata.feature
Reason:  
Type:  
Influences：  
   fix xx
=> 2.19.07.3 fix ci

behave_dble/assets/Btrace.md, behave_dble/assets/BtraceAboutsqlStatistic.java, behave_dble/features/func_test/dble_information/sql_statistic_basic.feature, behave_dble/features/func_test/dble_information/sql_statistic_by_table_by_user_by_entry.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Sql statistic

behave_dble/assets/Btrace.md, behave_dble/assets/BtraceAboutConnection.java, behave_dble/features/func_test/connection/connection_pool_valid_test.feature, behave_dble/features/steps/step_function.py
Reason:  
  Improve：http://10.186.18.11/jira/browse/DBLE0REQ-246
Type:  
Influences：  
   fix xx
=> Keep add connection pool valid test

behave_dble/features/func_test/dble_information/sql_statistic_by_frontend_by_backend_by_entry_by_user.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Keep sql table1

behave_dble/features/func_test/sql_plan/or_condition_calculation.feature, behave_dble/features/func_test/trace/trace_test.feature
http://10.186.18.11/jira/browse/DBLE0REQ-248
=> Keep or 248

behave_dble/features/func_test/dble_information/sql_log_and_tx_by_entry_user.feature, behave_dble/features/func_test/dble_information/sql_log_basic.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Keep sql log

behave_dble/features/func_test/xa_transaction/single_node_connect_exception.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue for 3.21.02

behave_dble/features/func_test/xa_transaction/net_down_before_rollback.feature, behave_dble/features/func_test/xa_transaction/single_node_connect_exception.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Fix ci issue 0412

behave_dble/features/func_test/cfg_test/db_value_incorrect.feature, behave_dble/features/func_test/dble_information/dble_sharding_node.feature, behave_dble/features/func_test/dble_information/processlist.feature, behave_dble/features/func_test/managercmd/create_and_drop_database.feature, behave_dble/features/func_test/sql_plan/route_single_node_across_databases.feature, behave_dble/features/sql_cover/special/support_special_sql.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case about 3.21.02 gitbub

behave_dble/assets/Btrace.md, behave_dble/assets/BtraceGeneralLog.java, behave_dble/features/func_test/cfg_test/general_log.feature, behave_dble/features/steps/step_install.py, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/GeneralLogTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/Main.java
Reason:  
Type:  
Influences：  
   fix xx
=> General log case

behave_dble/features/func_test/dble_information/dble_status.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update check questions/transactions case

behave_dble/features/func_test/dble_information/dble_status.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix_ci_issue_DBLE0REQ-1108

behave_dble/features/func_test/dble_information/dble_status.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix_ci_issue_transaction

behave_dble/features/func_test/dble_information/dble_status.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix_ci_issue_dble_status

behave_dble/features/func_test/connection/change_bootatrap_config.feature, behave_dble/features/steps/mysql_steps.py
Reason:  
Type:  
Influences：  
   fix xx
=> Keep chang bootstrap

drivers/Connector-.Net/netdriver/assets/sql/driver_test_manager.sql, drivers/Connector-J/assets/sql/driver_test_manager.sql, drivers/Connector-cpp/src/assets/sql/driver_test_manager.sql
Reason:  
Type:  
Influences：  
   fix xx
=> fix_ci_issue_driver remove Unsupported statement

behave_dble/features/func_test/cfg_test/server_side_cursor.feature, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/CapClientFoundRowsTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/Main.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/ServerSideCursorTest.java
Reason:  
Type:  
Influences：  
   fix xx
=> add server side cursor case

behave_dble/features/func_test/cfg_test/user_xml_blacklist.feature
Reason:  
Type:  
Influences：  
   fix xx
=> User xml blacklist

behave_dble/assets/BtraceGroupByThread.java, behave_dble/features/func_test/cfg_test/db_mincon_maxcon.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add minCon and maxCon case

drivers/jdbc-api-test/src/main/java/com/actiontech/dble/ServerSideCursorTest.java
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue - server side cursor

behave_dble/features/func_test/load_data/load_data_batch.feature
Reason:  
Type:  
Influences：  
   fix xx
=> delete "skip" tags in load_data_batch.feature

behave_dble/features/func_test/cfg_test/bootstrap_recordtxn.feature, behave_dble/features/steps/step_check_sql.py
Reason:  
Type:  
Influences：  
   fix xx
=> add txlog case - DBLE0REQ-853

behave_dble/features/func_test/load_data/load_data_batch.feature, behave_dble/features/steps/resultset_compare.py
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci error(adjust sleep time)

behave_dble/assets/BtraceAboutFlowControl.java, behave_dble/features/func_test/ddl/online_ddl.feature, behave_dble/features/func_test/flow_control/flow_control_complex.feature, behave_dble/features/func_test/flow_control/flow_control_loaddata.feature, behave_dble/features/func_test/flow_control/flow_control_simple.feature, behave_dble/features/func_test/flow_control/show_flow_control.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Keep flow control

behave_dble/features/environment.py
Reason:  
Type:  
Influences：  
   fix xx
=> remove repeat method about setting log level

behave_dble/features/func_test/dble_information/dble_xa_recover.feature, behave_dble/features/steps/RestoreEnvObject.py
Reason:  
Type:  
Influences：  
   fix xx
=> add case - check exception xa

behave_dble/features/environment.py, behave_dble/features/func_test/cfg_test/db_value_incorrect.feature, behave_dble/features/func_test/cfg_test/support_fake_host.feature, behave_dble/features/steps/step_install.py
Reason:  
Type:  
Influences：  
   fix xx
=> add case - support fake host

behave_dble/assets/BtraceClusterDelay.java, behave_dble/assets/BtraceLineDelay.java, behave_dble/features/cluster/cluster_check_reload.feature, behave_dble/features/func_test/connection/connection_leak_test.feature, behave_dble/features/func_test/managercmd/reload_lock.feature
Reason:  
Type:  
Influences：  
   fix xx
=> 06 regression

behave_dble/features/func_test/dble_information/session_variables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add "set session transaction read only"

behave_dble/features/func_test/sql_plan/operator_impact_to_route.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case about operator’s impact on routing

behave_dble/assets/BtraceMultiNodeMergeAndOrderHandler.java, behave_dble/features/func_test/cfg_test/inSubQueryTransformToJoin.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case - in to join

behave_dble/features/cluster/cluster_check_reload.feature, behave_dble/features/func_test/sql_plan/complexQuery_sendTo_oneNode.feature.feature, behave_dble/features/func_test/sql_plan/operator_impact_on_route.feature
=> Route to single node

drivers/jdbc-api-test/pom.xml, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/CachedRowSetSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/CapClientFoundRowsTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/ClobSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/CoffeesTable.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/ConnectionTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/DriverManagerTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/FilteredRowSetSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/GeneralLogTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/InterfaceTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/JDBCTutorialUtilities.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/JdbcRowSetSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/JoinSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/Main.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/ServerSideCursorTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/StatementTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/StoredProcedureMySQLSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/TestUtilities.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/WebRowSetSample.java
about DBLE0REQ-1010，adjust code structure, support mariadb_driver test
=> change for mariadb_driver API test

behave_dble/features/func_test/special/druid_support.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case - druid upgrade from 1.2.3 to 1.2.6

drivers/jdbc-api-test/src/main/java/com/actiontech/dble/CachedRowSetSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/CapClientFoundRowsTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/ClobSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/CoffeesTable.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/ConnProperties.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/ConnectionTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/DriverManagerTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/FilteredRowSetSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/GeneralLogTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/InterfaceTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/JDBCTutorialUtilities.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/JdbcRowSetSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/JoinSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/Main.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/ServerSideCursorTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/StatementTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/StoredProcedureMySQLSample.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/WebRowSetSample.java
Reason:  
Type:  
Influences：  
   fix xx
=> add toString method

behave_dble/features/steps/step_install.py
=> update method "stop_dble_in_node"

behave_dble/assets/BtraceMultiNodeMergeAndOrderHandler.java, behave_dble/features/func_test/xa_transaction/bg_strategy_after_node_hangs.feature, behave_dble/features/steps/step_function.py
Reason:  
Type:  
Influences：  
   fix xx
=> add case - check xaSessionCheckPeriod

behave_dble/assets/Btrace.md, behave_dble/assets/BtraceMultiNodeMergeAndOrderHandler.java, behave_dble/features/func_test/special/thread_leak_test.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case - check thread leak

behave_dble/features/func_test/xa_transaction/bg_strategy_after_node_hangs.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue - update xaSessionCheckPeriod

drivers/Connector-.Net/compare_result.sh, drivers/Connector-.Net/do_run_connector_dotnet.sh, drivers/Connector-.Net/run_connector_dotnet.sh, drivers/Connector-J/compare_result.sh, drivers/Connector-J/do_run_connector_J.sh, drivers/Connector-J/run_connector_J.sh, drivers/Connector-cpp/compare_result.sh, drivers/Connector-cpp/do_run_connector_cpp.sh, drivers/Connector-cpp/run_connector_cpp.sh, drivers/c_mysql_api/multi-queries/multiQuery.sh, drivers/c_mysql_api/src/c_mysql_api.sh
Reason:  
Type:  
Influences：  
   fix xx
=> try to resolve fail in shell

behave_dble/features/func_test/xa_transaction/bg_strategy_after_node_hangs.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue - update sleep time

drivers/Connector-J/src/main/java/com/actiontech/createFileUtil.java
Reason:  
  Improve 
Type:  
  Improve  
Influences：  
   fix xx
=> modify the reminder msg for coonnector J

behave_dble/run_func.sh, behave_dble/run_func_unstable.sh
Reason:  
Type:  
Influences：  
   fix xx
=> update ci task

behave_dble/run_func.sh, behave_dble/run_func_stable.sh, behave_dble/run_func_unstable.sh, behave_dble/run_func_unstable1.sh, behave_dble/run_func_unstable2.sh
Reason:  
Type:  
Influences：  
   fix xx
=> update ci task bash

behave_dble/run_cfg_test.sh, behave_dble/run_func_stable.sh, behave_dble/run_func_unstable.sh, behave_dble/run_manager_test.sh
Reason:  
Type:  
Influences：  
   fix xx
=> add "pipenv run"

drivers/Connector-cpp/run_connector_cpp.sh, drivers/c_mysql_api/multi-queries/multiQuery.sh, drivers/c_mysql_api/src/c_mysql_api.sh
Reason:  
Type:  
Influences：  
   fix xx
=> fix 'Host key verification failed' in ci

drivers/Connector-J/assets/sql/driver_test_manager.sql, drivers/Connector-J/std_sql_logs/driver_test_client_fail.log
Reason:  
Type:  
Influences：  
   fix xx
=> delete unsupported manage statement since 3.21.06.0

behave_dble/features/func_test/cfg_test/smoke_test.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix create too many aio threads

drivers/Connector-J/compare_result.sh, drivers/Connector-cpp/compare_result.sh
Reason:  
Type:  
Influences：  
   fix xx
=> update compare_result.sh for ci issue

behave_dble/compose/docker-build-behave/resetReplication.sh
Reason:  
  BUG
Type:  
  BUG
Influences：  
   fix xx
=> fix awk command not work fine in ssh romote mode

behave_dble/features/func_test/global_var_init/restore_global_var_when_reload.feature, behave_dble/features/func_test/heartbeat/kill_heartbeat_connection.feature, behave_dble/features/func_test/heartbeat/reconnect_heartbeat_readonly_check.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci fail for newReq 1347

behave_dble/features/func_test/dble_information/sql_statistic_queue_monitor.feature
Reason:  
  Add feature statistic_queue_monitor with py3 
Type:  
  feature 
Influences：  
   DBLE0REQ-978
=> Add feature: statistic_queue_monitor with py3

behave_dble/features/func_test/dble_information/dble_xa_recover.feature, behave_dble/features/func_test/dble_information/supported_DML_tables.feature, behave_dble/features/func_test/heartbeat/kill_heartbeat_connection.feature, behave_dble/features/func_test/managercmd/show_data_distribution.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci fail for 1347 and 1283

behave_dble/features/func_test/flow_control/show_flow_control.feature
Reason:  
Type:  
Influences：  
   fix xx
=> change flow control cases

behave_dble/features/steps/btrace_block.py
Reason:  
Type:  
Influences：  
   fix xx
=> update method about prepare btrace

behave_dble/features/steps/btrace_block.py
Reason:  
Type:  
Influences：  
   fix xx
=> add count to check btrace status

behave_dble/features/func_test/dble_information/table_support_select.feature, behave_dble/features/func_test/managercmd/show_help.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci fail managerTest instance 24

behave_dble/features/func_test/dble_information/dble_schema.feature, behave_dble/features/func_test/dble_information/dble_sharding_node.feature, behave_dble/features/func_test/dble_information/table_support_select.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issues

behave_dble/assets/Btrace.md, behave_dble/assets/BtraceClusterDelay.java, behave_dble/features/cluster/cluster_check_reload.feature, behave_dble/features/func_test/cfg_test/metadata_fault_tolerance.feature, behave_dble/features/func_test/cfg_test/mulitiple_reload.feature
Reason:  
Type:  
Influences：  
   fix xx
=> modify for btrace change and msg change

behave_dble/features/steps/lib/utils.py
Reason:  
Type:  
Influences：  
   fix xx
=> remove repeat output_log and raise error

behave_dble/features/steps/lib/utils.py
Reason:  
Type:  
Influences：  
   fix xx
=> remove unnecessary finally

behave_dble/features/func_test/cfg_test/Exception_sharding.feature
Reason:  
Type:  
Influences：  
   fix xx
=> amend the hint msg

behave_dble/features/func_test/cfg_test/user_xml_blacklist.feature
Reason:  
Type:  
Influences：  
   fix xx
=> rwSplit user supports blacklist function

behave_dble/features/steps/step_install.py
Reason:  
  Improve #.  
Type:  
Influences：  
   fix xx
=> optimize install dble

behave_dble/features/cluster/zk_onlinekey_check.feature, behave_dble/features/steps/step_function.py, behave_dble/features/steps/step_install.py
Reason:  
  BUG 
Type:  
Influences：  
   fix xx
=> amend wrong code

behave_dble/features/func_test/sharding_func_test/date.feature
Reason:  
Type:  
Influences：  
   fix xx
=> modify the msg

behave_dble/features/func_test/cfg_test/support_fake_host.feature, behave_dble/features/func_test/managercmd/python_mysql_ha.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci fail for cfgtest 49

behave_dble/features/cluster/cluster_file_syn.feature, behave_dble/features/steps/step_install.py
Reason:  
Type:  
Influences：  
   fix xx
=> function file should be synchronized to each node

behave_dble/delete_all_mysql_tables.sh, behave_dble/features/func_test/cfg_test/schema_funcation.feature, behave_dble/features/steps/RestoreEnvObject.py, behave_dble/features/steps/lib/utils.py
Reason:  
  for some cases need to avoid backend mysql tables influence  that forget deleting after scenario
Type:  
Influences：  
   fix xx
=> add two ways to clear backend mysql tables

behave_dble/assets/Btrace.md, behave_dble/assets/BtraceClusterDetachAttach1.java, behave_dble/assets/BtraceClusterDetachAttach2.java, behave_dble/assets/BtraceClusterDetachAttach3.java, behave_dble/assets/BtraceClusterDetachAttach4.java, behave_dble/assets/BtraceClusterDetachAttach5.java, behave_dble/assets/BtraceClusterDetachAttach6.java, behave_dble/features/cluster/cluster_detach_attach.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add cluster detach, attach case

behave_dble/features/cluster/cluster_detach_attach.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue - update bootstrap.cnf parameters

behave_dble/features/func_test/special/fingerprint_log.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add fingerprint log case

behave_dble/features/func_test/special/fingerprint_log.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update fingerprint log case

behave_dble/compose/dbdeployer_deploy_mysql.sh
Reason:  
Improve #.   http://10.186.18.11/jira/browse/DBLE0REQ-1346
Type:  
Influences：  
   fix xx
=> add login mysql with no-password

behave_dble/compose/docker-build-dble/Dockerfile
Reason:  
  Improve #.  http://10.186.18.11/jira/browse/DBLE0REQ-1341
Type:  
Influences：  
   fix xx
=> fix dble-related images lang problem

behave_dble/features/steps/step_check_sql.py, behave_dble/sqls/manager/manager.sql
Reason:  
  BUG #. or Improve #.  inner 1459
Type:  
Influences：  
   fix xx
=> solve problem about connection not close used in thread

behave_dble/features/steps/lib/utils.py, behave_dble/std_sql_cover_global/sqls_util/select/expression_fail.log, behave_dble/std_sql_cover_mixed/sqls_mixed/select/subquery_dev_serious_warn.log, behave_dble/std_sql_cover_mixed/sqls_mixed/select/subquery_dev_warn.log
Reason:  
Type:  
Influences：  
   fix xx
=> format log

behave_dble/features/func_test/xa_transaction/bg_strategy_after_net_shock.feature, behave_dble/features/steps/btrace_block.py
Reason:  
  Improve #.  
Type:  
Influences：  
   fix xx
=> amend xa case and reduce check btrace log timeout

behave_dble/std_sql_cover_mixed/sqls_mixed/select/subquery_dev_serious_warn.log, behave_dble/std_sql_cover_nosharding/sqls_util/syntax/view_serious_warn.log
Reason:  
Type:  
Influences：  
   fix xx
=> update std_sql_log for ci failed

behave_dble/std_sql_cover_global/sqls_util/syntax/view_serious_warn.log, behave_dble/std_sql_cover_nosharding/sqls_util/syntax/view_serious_warn.log
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue - update dble errorno

behave_dble/features/func_test/dble_information/dble_variables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue - add variable: rwStickyTime

behave_dble/features/environment.py, behave_dble/features/steps/lib/DbleObject.py, behave_dble/features/steps/lib/MySQLObject.py, behave_dble/features/steps/mysql_steps.py
Reason:  
  DBLE0REQ-1514
Type:  
Influences：  
   fix xx
=> fix problem about dble and mysql connection conflict

behave_dble/features/func_test/sql_plan/useNewJoinOptimizer.feature, behave_dble/features/steps/dble_steps.py
Reason:  
Type:  
Influences：  
   fix xx
=> add function used compare resultSet with mysql

behave_dble/features/sql_cover/special/hint.feature, behave_dble/sqls/sqls_mixed/bugs/bug.sql
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue - DBLE0REQ-1541

behave_dble/README.md, behave_dble/features/steps/RestoreEnvObject.py
Reason:  
  inner  DBLE0REQ-1539
Type:  
Influences：  
   fix xx
=> update @delete_mysql_tables tag

behave_dble/features/sql_cover/special/hint.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update error message

behave_dble/features/func_test/sql_plan/useNewJoinOptimizer.feature
Reason:  
Type:  
Influences：  
   fix xx
=> release union select

behave_dble/features/func_test/sql_plan/useNewJoinOptimizer.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add compare table in mysql

behave_dble/dble_conf/sql_cover_global_bk/bootstrap.cnf, behave_dble/dble_conf/sql_cover_mixed_bk/bootstrap.cnf, behave_dble/dble_conf/sql_cover_nosharding_bk/bootstrap.cnf, behave_dble/dble_conf/sql_cover_sharding_bk/bootstrap.cnf, behave_dble/features/func_test/sql_plan/useNewJoinOptimizer.feature
Reason:  
Type:  
Influences：  
   fix xx
=> test sql cover with useNewJoinOptimizer

behave_dble/features/func_test/cfg_test/inSubQueryTransformToJoin.feature, behave_dble/features/func_test/sql_plan/complexQuery_sendTo_oneNode.feature, behave_dble/features/sql_cover/special/chinese_comment.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update sql plan

behave_dble/features/func_test/cfg_test/bootstrap_recordtxn.feature, behave_dble/features/func_test/dble_information/backend_variables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> singleTable's DDL will be recorded

behave_dble/std_sql_cover_mixed/sqls_mixed/syntax/identifiers_fail.log
Reason:  
Type:  
Influences：  
   fix xx
=> update std error log

behave_dble/features/func_test/cfg_test/bootstrap_recordtxn.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update xid begin from 0

behave_dble/features/cluster/cluster_check_Ha.feature, behave_dble/features/func_test/cfg_test/db_value_incorrect.feature, behave_dble/features/func_test/dble_information/dble_variables.feature, behave_dble/features/func_test/managercmd/show_heartbeat.feature, behave_dble/features/sql_cover/special/chinese_comment.feature, behave_dble/features/steps/resultset_compare.py
Reason:  
Type:  
Influences：  
   fix xx
=> 3.21.02 fix ci

behave_dble/features/func_test/sql_plan/or_condition_calculation.feature, behave_dble/features/func_test/sql_plan/route_single_node_across_databases.feature, behave_dble/features/func_test/sql_plan/useNewJoinOptimizer3.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case check join order

behave_dble/assets/BtraceAddMetaLock.java, behave_dble/features/func_test/metalock/mysql_slave_down.feature, behave_dble/features/sql_cover/special/chinese_comment.feature
Reason:  
Type:  
Influences：  
   fix xx
=> adjust DDL btrace and related case

behave_dble/dble_conf/sql_cover_global_bk/bootstrap.cnf, behave_dble/dble_conf/sql_cover_mixed_bk/bootstrap.cnf, behave_dble/dble_conf/sql_cover_nosharding_bk/bootstrap.cnf, behave_dble/dble_conf/sql_cover_sharding_bk/bootstrap.cnf
Reason:  
Type:  
Influences：  
   fix xx
=> restore bootstrap.cnf

behave_dble/features/func_test/dble_information/dble_variables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update variables number

behave_dble/features/func_test/dble_information/dble_variables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update variables number again

behave_dble/std_sql_cover_mixed/sqls_mixed/syntax/set_user_var_fail.log
Reason:  
Type:  
Influences：  
   fix xx
=> update std dble error log

behave_dble/features/func_test/ddl/ddl_refactor.feature
Reason:  
  inner 1447
Type:  
Influences：  
   fix xx
=> update ddl log

behave_dble/features/func_test/dble_information/dble_xa_recover.feature, behave_dble/features/steps/step_function.py
Reason:  
Type:  
Influences：  
   fix xx
=> update grep content and support "'"

behave_dble/features/func_test/cfg_test/support_rownum.feature, behave_dble/features/steps/step_install.py
Reason:  
Type:  
Influences：  
   fix xx
=> add case - support rownum sql

behave_dble/features/cluster/cluster_check_Ha.feature, behave_dble/features/cluster/cluster_check_table_ddl.feature, behave_dble/features/cluster/cluster_detach_attach.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update err message and remove RW load

behave_dble/assets/Btrace.md, behave_dble/assets/BtraceRwSelect.java, behave_dble/assets/BtraceSelectRWDbGroup.java, behave_dble/features/func_test/connection/rwSplit_connection_test.feature, behave_dble/features/steps/mysql_steps.py, behave_dble/std_sql_cover_mixed/sqls_mixed/syntax/identifiers_fail.log
Reason:  
  inner 1572
Type:  
Influences：  
   fix xx
=> Add case about rw split

behave_dble/features/cluster/cluster_check_ddl_log.feature, behave_dble/features/func_test/ddl/ddl_refactor.feature, behave_dble/features/steps/step_check_sql.py, behave_dble/features/steps/step_function.py
Reason:  
Type:  
Influences：  
   fix xx
=> add case about cluster ddl log check

behave_dble/features/cluster/cluster_check_zk_binlog.feature, behave_dble/features/func_test/connection/connection_pool_valid_test.feature, behave_dble/features/func_test/connection/rwSplit_connection_test.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci error

behave_dble/features/func_test/connection/change_bootatrap_config.feature
Reason:  
  for inner 1384
Type:  
Influences：  
   fix xx
=> update thread name used in bootstrap.cnf for inner-1384

behave_dble/features/func_test/cfg_test/bootstrap_value_valid.feature, behave_dble/features/func_test/cfg_test/template_value_correct.feature
Reason:  
Type:  
Influences：  
   fix xx
=> thread name in metadata need to update

behave_dble/features/func_test/dble_information/supported_DML_tables.feature, behave_dble/features/func_test/managercmd/python_mysql_ha.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add escape characters

behave_dble/features/func_test/cfg_test/bootstrap_value_valid.feature, behave_dble/features/func_test/connection/change_bootatrap_config.feature, behave_dble/features/func_test/connection/rwSplit_connection_test.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add skip tag for bug

behave_dble/features/func_test/dble_information/dble_thread_usage.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update thread name and skip

behave_dble/behave.ini, behave_dble/compose/update_dble_version.sh, behave_dble/conf/auto_dble_test.yaml, behave_dble/features/steps/step_install.py, drivers/Connector-.Net/netdriver/conf/auto_dble_test.yaml, drivers/Connector-J/conf/auto_dble_test.yaml, drivers/Connector-cpp/src/conf/auto_dble_test.yaml
Reason:  
Type:  
Influences：  
   fix xx
=> remove ftp user

behave_dble/features/environment.py
config CI environment variables
=> config CI environment variables

behave_dble/features/environment.py, behave_dble/features/steps/step_install.py
fix config CI environment variables
=> fix config CI environment variables

behave_dble/features/func_test/connection/change_bootatrap_config.feature, behave_dble/features/func_test/dble_information/dble_thread_usage.feature
Reason:  
Type:  
Influences：  
   fix xx
=> release cases for issue has been fixed

behave_dble/features/func_test/cfg_test/inSubQueryTransformToJoin.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add cases about hint with in2join

drivers/Connector-.Net/compare_result.sh, drivers/Connector-.Net/netdriver/assets/sql/driver_test_client.sql, drivers/Connector-J/assets/sql/driver_test_client.sql, drivers/Connector-J/compare_result.sh, drivers/Connector-J/do_run_connector_J.sh, drivers/Connector-cpp/compare_result.sh
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue - update script and sql

behave_dble/assets/BtraceAddMetaLockForOnce.java, behave_dble/features/func_test/metalock/ddl_meta_lock.feature
Reason:  
  inner 1615
Type:  
Influences：  
   fix xx
=> test with ddl meta lock

behave_dble/features/func_test/connection/rwSplit_connection_test.feature, behave_dble/features/steps/mysql_steps.py
Reason:  
Type:  
Influences：  
   fix xx
=> Update connection test

behave_dble/assets/Btrace.md, behave_dble/assets/BtraceSessionStage.java, behave_dble/features/func_test/connection/kill_front_connection.feature
Reason:  
  fix ci http://10.186.18.19:8153/go/tab/build/detail/autoTest_dble_funcTest/217/unstable_test/1/unstable_test
（Occasional appearance）
Type:  
Influences：  
   fix xx
=> change btrace to avoid heartbeat timeout

behave_dble/features/steps/lib/PostQueryCheck.py
Reason:  
Type:  
Influences：  
   fix xx
=> add result check about equal

behave_dble/features/func_test/dble_information/dble_xa_recover.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add sleep for ci failed

behave_dble/features/func_test/dble_information/dble_variables.feature, behave_dble/features/func_test/sql_plan/useNewJoinOptimizer1.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add new dble variables

behave_dble/features/func_test/sql_plan/operator_impact_on_route.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue - DBLE0REQ-1467

behave_dble/features/cluster/zk_global_sequence.feature, behave_dble/features/func_test/sequence/ts_global_sequence.feature, behave_dble/features/steps/lib/utils.py
Reason:  
Type:  
Influences：  
   fix xx
=> skip cases about change system time

behave_dble/features/func_test/cfg_test/support_rownum.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update rownum case

behave_dble/features/func_test/cfg_test/support_rownum.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update rownum case - update PARAM_DESCR

behave_dble/features/func_test/cfg_test/bootstrap_value_valid.feature
Reason:  
Type:  
Influences：  
   fix xx
=> correct processors name

behave_dble/assets/BtraceAboutConnection.java, behave_dble/features/func_test/dble_information/backend_connections.feature
Reason:  
  inner-1624
Type:  
Influences：  
   fix xx
=> Check backend connection status

behave_dble/assets/BtraceAboutConnection.java, behave_dble/features/func_test/dble_information/backend_connections.feature, behave_dble/features/func_test/managercmd/show_help.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Update for ci

behave_dble/features/cluster/cluster_xml_to_json.feature, behave_dble/features/func_test/cfg_test/xml_to_json.feature
Reason:  
  see DBLE0REQ-1715 
Type:  
Influences：  
   fix xx
=> add new parameter

behave_dble/features/func_test/cfg_test/bootstrap_rwStickyTime.feature
=> Keep rw sticky time

behave_dble/features/func_test/sql_plan/hint_ruleBCD_1.feature, behave_dble/features/func_test/sql_plan/hint_ruleBCD_2.feature, behave_dble/features/func_test/sql_plan/hint_ruleBCD_3.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add case - hint rule BCD

behave_dble/features/func_test/sql_plan/check_sql_plan.feature, behave_dble/features/func_test/sql_plan/check_user_hint.feature, behave_dble/features/steps/step_install.py
Reason:  
Type:  
Influences：  
   fix xx
=> add case about issue

drivers/jdbc-api-test/src/main/java/com/actiontech/dble/Main.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/RwSplitUserPsTest.java, drivers/jdbc-api-test/src/main/java/com/actiontech/dble/RwSplitUserTest.java
Reason:  
Type:  
Influences：  
   fix xx
=> add case - rwSplitUser ps case

drivers/jdbc-api-test/src/main/java/com/actiontech/dble/RwSplitUserPsTest.java
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue about rwSplitUser ps

behave_dble/features/func_test/dble_information/dble_variables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add ssl parameter

behave_dble/features/func_test/connection/transaction_connection_test.feature
Reason:  
Type:  
Influences：  
   fix xx
=> inner-1744 cases

behave_dble/features/func_test/dble_information/dble_xa_recover.feature
Reason:  
Type:  
Influences：  
   fix xx
=> xid format changed

behave_dble/features/func_test/xa_transaction/xa_node_result_diff.feature
Reason:  
Type:  
Influences：  
   fix xx
=> changed due to xid format recover as before

behave_dble/features/func_test/connection/transaction_connection_test.feature, behave_dble/features/steps/step_install.py
Reason:  
Type:  
Influences：  
   fix xx
=> Delay detection

behave_dble/README.md, behave_dble/assets/schema1_with_childTable.sql, behave_dble/assets/schema1_with_only_table_structure.sql, behave_dble/assets/schema1_with_view.sql, behave_dble/assets/schema2_with_no_default_shardingNode.sql, behave_dble/features/func_test/managercmd/split.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update split feature

drivers/Connector-.Net/compare_result.sh, drivers/Connector-.Net/do_run_connector_dotnet.sh, drivers/Connector-.Net/run_connector_dotnet.sh, drivers/Connector-J/compare_result.sh, drivers/Connector-J/do_run_connector_J.sh, drivers/Connector-J/run_connector_J.sh, drivers/Connector-cpp/compare_result.sh, drivers/Connector-cpp/do_run_connector_cpp.sh, drivers/Connector-cpp/run_connector_cpp.sh, drivers/c_mysql_api/multi-queries/multiQuery.sh, drivers/c_mysql_api/src/c_mysql_api.sh
add exit flag for ci check status success-inner-1090
Reason:  
Type:  
Influences：  
   fix xx
=> add exit flag for ci check status success

behave_dble/features/func_test/cfg_test/user_rwSplitUser.feature, behave_dble/features/func_test/dble_information/dble_variables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue master 318

behave_dble/features/func_test/cfg_test/user_rwSplitUser.feature, behave_dble/features/func_test/cfg_test/xml_to_json.feature, behave_dble/features/func_test/dble_information/dble_db_instance.feature, behave_dble/features/func_test/dble_information/dble_variables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue 22.01 30

behave_dble/features/func_test/cfg_test/user_rwSplitUser.feature, behave_dble/features/func_test/dble_information/dble_variables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue master 318 (#522)

behave_dble/features/func_test/cfg_test/user_rwSplitUser.feature, behave_dble/features/func_test/cfg_test/xml_to_json.feature, behave_dble/features/func_test/dble_information/dble_variables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci 2201 35

behave_dble/features/func_test/cfg_test/user_rwSplitUser.feature, behave_dble/features/func_test/dble_information/dble_variables.feature, behave_dble/features/func_test/dble_information/table_support_select.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Fix ci master 2157

behave_dble/features/func_test/dble_information/dble_variables.feature
=> fix ci 2201 

behave_dble/features/sql_cover/special/hint.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix_log_bin_trust_function_creators

behave_dble/features/cluster/cluster_check_table_ddl.feature, behave_dble/features/func_test/metalock/ddl_meta_lock.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update err message: inner-1646

behave_dble/features/steps/step_install.py
Reason:  
Type:  
Influences：  
   fix xx
=> optimize stop dble method

behave_dble/features/func_test/cfg_test/user_rwSplitUser.feature, behave_dble/features/func_test/dble_information/dble_db_instance.feature, behave_dble/features/func_test/dble_information/dble_variables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Fix ci master 2189

behave_dble/features/steps/RestoreEnvObject.py
Reason:  
Type:  
Influences：  
   fix xx
=> optimize delete mysql tables

behave_dble/features/func_test/sql_plan/useJoinStrategy1.feature, behave_dble/features/func_test/sql_plan/useJoinStrategy2.feature, behave_dble/features/func_test/sql_plan/useJoinStrategy3.feature, behave_dble/features/func_test/sql_plan/useJoinStrategy4.feature, behave_dble/features/func_test/sql_plan/useJoinStrategy5.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add useJoinStrategy case

behave_dble/features/cluster/cluster_check_reload.feature, behave_dble/features/cluster/cluster_check_start.feature, behave_dble/features/cluster/cluster_xml_to_json.feature, behave_dble/features/cluster/ruleFile.feature, behave_dble/features/func_test/cfg_test/xml_to_json.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue - add specifyCharset

behave_dble/features/cluster/cluster_check_reload.feature, behave_dble/features/cluster/cluster_check_start.feature, behave_dble/features/cluster/cluster_xml_to_json.feature, behave_dble/features/cluster/ruleFile.feature, behave_dble/features/func_test/cfg_test/inSubQueryTransformToJoin.feature, behave_dble/features/func_test/cfg_test/xml_to_json.feature, behave_dble/features/func_test/sql_plan/hint_DirectedAcyclicGraph_RightJoin_1.feature, behave_dble/features/func_test/sql_plan/hint_DirectedAcyclicGraph_RightJoin_2.feature, behave_dble/features/func_test/sql_plan/hint_DirectedAcyclicGraph_RightJoin_3.feature, behave_dble/features/func_test/sql_plan/hint_planA_1.feature, behave_dble/features/func_test/sql_plan/hint_planA_2.feature, behave_dble/features/func_test/sql_plan/hint_planA_3.feature, behave_dble/features/func_test/sql_plan/hint_planA_4.feature, behave_dble/features/func_test/sql_plan/hint_planA_5.feature, behave_dble/features/func_test/sql_plan/hint_planA_6.feature, behave_dble/features/func_test/sql_plan/hint_ruleBCD_1.feature, behave_dble/features/func_test/sql_plan/hint_ruleBCD_2.feature, behave_dble/features/func_test/sql_plan/hint_ruleBCD_3.feature, behave_dble/features/func_test/sql_plan/left2inner.feature, behave_dble/features/func_test/sql_plan/useNewJoinOptimizer1.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Fix issue - skip hint fail case

behave_dble/features/func_test/cfg_test/support_fake_host.feature, behave_dble/features/func_test/connection/connection_leak_test.feature, behave_dble/features/func_test/connection/rwSplit_connection_test.feature, behave_dble/features/func_test/dble_information/supported_DML_tables.feature, behave_dble/features/func_test/dble_information/table_support_select.feature, behave_dble/features/func_test/global_var_init/start_fail_if_lettercase_different.feature, behave_dble/features/func_test/heartbeat/kill_heartbeat_connection.feature, behave_dble/features/func_test/heartbeat/reconnect_heartbeat_readonly_check.feature, behave_dble/features/func_test/managercmd/create_and_drop_database.feature, behave_dble/features/func_test/managercmd/python_mysql_ha.feature, behave_dble/features/func_test/managercmd/reload_config_all_s.feature, behave_dble/features/func_test/safety/mysql_node_disconnected.feature, behave_dble/features/func_test/special/fingerprint_log.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci issue - add skip about DBLE0REQ-1793

behave_dble/features/func_test/cfg_test/support_fake_host.feature, behave_dble/features/func_test/dble_information/supported_DML_tables.feature, behave_dble/features/func_test/global_var_init/start_fail_if_lettercase_different.feature, behave_dble/features/func_test/heartbeat/kill_heartbeat_connection.feature, behave_dble/features/func_test/heartbeat/reconnect_heartbeat_readonly_check.feature, behave_dble/features/func_test/managercmd/python_mysql_ha.feature, behave_dble/features/func_test/managercmd/reload_config_all_fs.feature, behave_dble/features/func_test/safety/mysql_node_disconnected.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update reload case

behave_dble/features/func_test/managercmd/python_mysql_ha.feature
Reason:  
Type:  
Influences：  
   fix xx
=> change case about mysql_ha

behave_dble/conf/auto_dble_test.yaml, behave_dble/features/environment.py, behave_dble/features/func_test/connection/connection_leak_test.feature
Reason:  
Type:  
Influences：  
   fix xx
=> redefine auto_retry

behave_dble/features/func_test/cfg_test/sharding_db_attribute.feature, behave_dble/features/steps/step_createConn.py
Reason:  
Type:  
Influences：  
   fix xx
=> optimize create conn used in thread

behave_dble/assets/BtraceAboutConnection.java
Reason:  
Type:  
Influences：  
   fix xx
=> change btrace class

behave_dble/assets/BtraceRwSplitSession.java, behave_dble/features/func_test/connection/rwSplit_connection_test.feature
Reason:  
Type:  
Influences：  
   fix xx
=> update rwSplit case

behave_dble/features/func_test/cfg_test/user_rwSplitUser.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add necessary sleep

behave_dble/features/func_test/dble_information/dble_db_instance.feature, behave_dble/features/func_test/managercmd/reload_config_all_fs.feature, behave_dble/features/func_test/managercmd/show_heartbeat.feature
Reason:  
Type:  
Influences：  
   fix xx
=> upper character

behave_dble/features/func_test/global_var_init/restore_global_var_when_reload.feature
Reason:  
Type:  
Influences：  
   fix xx
=> mysql global var check times changed

behave_dble/features/cluster/cluster_xml_to_json.feature, behave_dble/features/func_test/cfg_test/xml_to_json.feature, behave_dble/features/func_test/dble_information/supported_DML_tables.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add new param keepAlive

behave_dble/features/func_test/managercmd/slow_query.feature
Reason:  
Type:  
Influences：  
   fix xx
=> Keep 1803 slowlog

behave_dble/features/func_test/connection/connection_leak_test.feature, behave_dble/features/func_test/connection/connection_pool_basic_test.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci about 2290 due to add sleep time

behave_dble/features/func_test/dble_information/dble_variables.feature, behave_dble/features/func_test/dble_information/dble_xa_recover.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci about 2992 due to add enableAsyncRelease and releaseTimeout

behave_dble/features/func_test/sql_plan/hint_use_table_index.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add use table index case

behave_dble/features/func_test/cfg_test/db_stable.feature, behave_dble/features/func_test/cfg_test/user_rwSplitUser.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci about 2296 about add sleeptime

behave_dble/features/func_test/connection/change_bootatrap_config.feature, behave_dble/features/func_test/ddl/ddl_refactor.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci about 2298 about frontworker

behave_dble/features/func_test/sql_plan/hint_ruleBCD_3.feature, behave_dble/features/func_test/sql_plan/joinStrategyType4.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci about 2302 about add where 1=1

behave_dble/features/cluster/cluster_check_ddl_log.feature, behave_dble/features/func_test/connection/connection_pool_basic_test.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci about 2310 change "select count(*)" to "select *"

behave_dble/features/func_test/sql_plan/hint_DirectedAcyclicGraph_RightJoin_3.feature, behave_dble/features/func_test/sql_plan/hint_ruleBCD_3.feature, behave_dble/features/func_test/sql_plan/joinStrategyType4.feature, behave_dble/features/func_test/sql_plan/left2inner.feature, behave_dble/features/func_test/sql_plan/useJoinStrategy4.feature, behave_dble/features/func_test/sql_plan/useNewJoinOptimizer1.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci - add where 1=1

behave_dble/features/func_test/connection/connection_pool_basic_test.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci fail case

behave_dble/compose/start_env.sh
Reason:  
Type:  
Influences：  
   fix xx
=> change start_env.sh

behave_dble/features/steps/step_install.py
=> adjust the way to stop dble

behave_dble/features/func_test/heartbeat/kill_heartbeat_connection.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci about 104 function

behave_dble/conf/auto_dble_test.yaml, behave_dble/features/func_test/managercmd/create_and_drop_database.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci about 53 adjust timeBetweenEvictionRunsMillis and idleTimeout

behave_dble/features/func_test/cfg_test/sharding_db_attribute.feature
Reason:  
Type:  
Influences：  
   fix xx
=> fix ci about 106 adjust timeBetweenEvictionRunsMillis and idleTimeout

behave_dble/compose/docker-compose-cluster.yml, behave_dble/compose/docker-compose-single.yml
Reason:  
Type:  
  Improve  
Influences：  
   modify docker compose file with serveral ports exposed
=> Add  expose port

behave_dble/features/func_test/managercmd/python_mysql_ha.feature
Reason:  
Type:  
Influences：  
   fix xx
=> add xargs -r when kill python script

behave_dble/features/func_test/cfg_test/user_rwSplitUser.feature, behave_dble/features/func_test/dble_information/dble_variables.feature, behave_dble/features/func_test/managercmd/show_help.feature
Reason:  
Type:  
Influences：  
   fix xx
=> adjust about sql_dump_log case

behave_dble/features/func_test/dble_information/dble_status.feature, behave_dble/features/func_test/dble_information/sql_statistic.feature
Reason:  
Type:  
Influences：  
   fix xx
=> adjust about transactions case

behave_dble/features/cluster/cluster_check_start.feature, behave_dble/features/cluster/cluster_xml_to_json.feature, behave_dble/features/cluster/ruleFile.feature, behave_dble/features/func_test/cfg_test/xml_to_json.feature
Reason:  
Type:  
Influences：  
   fix xx
=> adjust about logicalCreateADrop case

behave_dble/compose/README.md
Reason:  
Type:  
Influences：  
   fix xx
=> modify readme
